apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: name
  namespace: p0-namespace
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: rrr.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mongo-express-service
                port:
                  number: 8081
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   namespace: ingress-nginx
#   name: ingress-nginx-controller
#   annotations:
#     metallb.universe.tf/address-pool: my-ip-space
# spec:
#   type: LoadBalancer
#   selector:
#     app.kubernetes.io/component: controller
#   ports:
#     - name: http
#       port: 80
#       targetPort: http
#     - name: https
#       port: 443
#       targetPort: https
