apiVersion: v1
kind: Namespace
metadata:
  name: p0-namespace
---
apiVersion: v1
kind: LimitRange
metadata:
  name: p0-namespace-limits
  namespace: p0-namespace
spec:
  limits:
    - default:
        memory: 256Mi
        cpu: 200m
      defaultRequest:
        memory: 128Mi
        cpu: 100m
      type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: p0-namespace-quota
  namespace: p0-namespace
spec:
  hard:
    limits.memory: 2Gi
    limits.cpu: "2"
    pods: "10"
    configmaps: "10"
    services: "10"
    persistentvolumeclaims: "5"
    secrets: "5"
