apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: p0-namespace
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /home/rgioanca/project-zero/mongodb
  claimRef:
    name: mongodb-pvc
    namespace: p0-namespace
